#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Exercise_4.Resource", IsApplication=true)]

namespace Exercise_4
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f030001
			public const int operationTextSize = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int resultTextSize = 2130903040;
			
			// aapt resource value: 0x7f030003
			public const int textSizeLarge = 2130903043;
			
			// aapt resource value: 0x7f030002
			public const int viewGroupMargin = 2130903042;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050015
			public const int btnAdd = 2131034133;
			
			// aapt resource value: 0x7f050005
			public const int btnC = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int btnCE = 2131034118;
			
			// aapt resource value: 0x7f050011
			public const int btnChangeStatus = 2131034129;
			
			// aapt resource value: 0x7f050007
			public const int btnDel = 2131034119;
			
			// aapt resource value: 0x7f050018
			public const int btnDiv = 2131034136;
			
			// aapt resource value: 0x7f050013
			public const int btnDot = 2131034131;
			
			// aapt resource value: 0x7f050009
			public const int btnEight = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int btnFive = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int btnFour = 2131034123;
			
			// aapt resource value: 0x7f050017
			public const int btnMul = 2131034135;
			
			// aapt resource value: 0x7f05000a
			public const int btnNine = 2131034122;
			
			// aapt resource value: 0x7f05000e
			public const int btnOne = 2131034126;
			
			// aapt resource value: 0x7f050008
			public const int btnSeven = 2131034120;
			
			// aapt resource value: 0x7f05000d
			public const int btnSix = 2131034125;
			
			// aapt resource value: 0x7f050019
			public const int btnSolve = 2131034137;
			
			// aapt resource value: 0x7f050016
			public const int btnSub = 2131034134;
			
			// aapt resource value: 0x7f050010
			public const int btnThree = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int btnTwo = 2131034127;
			
			// aapt resource value: 0x7f050012
			public const int btnZero = 2131034130;
			
			// aapt resource value: 0x7f050002
			public const int linearLayout1 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int linearLayout2 = 2131034115;
			
			// aapt resource value: 0x7f050014
			public const int linearLayout3 = 2131034132;
			
			// aapt resource value: 0x7f050004
			public const int linearLayout4 = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int txtExpression = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int txtResult = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040012
			public const int btnAC = 2130968594;
			
			// aapt resource value: 0x7f04000c
			public const int btnAdd = 2130968588;
			
			// aapt resource value: 0x7f040011
			public const int btnC = 2130968593;
			
			// aapt resource value: 0x7f040013
			public const int btnChangeStatus = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int btnDel = 2130968596;
			
			// aapt resource value: 0x7f04000e
			public const int btnDiv = 2130968590;
			
			// aapt resource value: 0x7f04000b
			public const int btnDot = 2130968587;
			
			// aapt resource value: 0x7f040009
			public const int btnEight = 2130968585;
			
			// aapt resource value: 0x7f040006
			public const int btnFive = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int btnFour = 2130968581;
			
			// aapt resource value: 0x7f04000f
			public const int btnMul = 2130968591;
			
			// aapt resource value: 0x7f04000a
			public const int btnNine = 2130968586;
			
			// aapt resource value: 0x7f040002
			public const int btnOne = 2130968578;
			
			// aapt resource value: 0x7f040008
			public const int btnSeven = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int btnSix = 2130968583;
			
			// aapt resource value: 0x7f040010
			public const int btnSolve = 2130968592;
			
			// aapt resource value: 0x7f04000d
			public const int btnSub = 2130968589;
			
			// aapt resource value: 0x7f040004
			public const int btnThree = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int btnTwo = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int btnZero = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
