#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Exercise_5.Resource", IsApplication=true)]

namespace Exercise_5
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int firstArray = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int secondArray = 2131099649;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int viewGroupMargin = 2130968576;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int backarrow = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090001
			public const int button1 = 2131296257;
			
			// aapt resource value: 0x7f090005
			public const int editText1 = 2131296261;
			
			// aapt resource value: 0x7f090007
			public const int editText2 = 2131296263;
			
			// aapt resource value: 0x7f09000a
			public const int item1 = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int item2 = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int item3 = 2131296268;
			
			// aapt resource value: 0x7f090003
			public const int linearLayout1 = 2131296259;
			
			// aapt resource value: 0x7f090006
			public const int linearLayout2 = 2131296262;
			
			// aapt resource value: 0x7f090008
			public const int spinner1 = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int spinner2 = 2131296265;
			
			// aapt resource value: 0x7f090002
			public const int textView1 = 2131296258;
			
			// aapt resource value: 0x7f090004
			public const int textView2 = 2131296260;
			
			// aapt resource value: 0x7f090000
			public const int toolbar = 2131296256;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int menu = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050007
			public const int Address = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int Connors = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int Date = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int FirstName = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int ResidenceAddress = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int SocialSecurity = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int ZipCode = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int city = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int header = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int MyTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
