#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Exercise_3.Resource", IsApplication=true)]

namespace Exercise_3
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f030000
			public const int white = 2130903040;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040003
			public const int marginLarge = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int marginSmall = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int paddingLarge = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int paddingSmall = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int textSizeLarge = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int textSizeMedium = 2130968580;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060005
			public const int btnReset = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int btnSolve = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int edFirstCofficient = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int edSecondCofficient = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int edThirdCofficient = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int linearLayout5 = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int tvResult = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int tvResultTitle = 2131099654;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050008
			public const int InfiniteSolution = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int InputData = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int InputFloat = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int NoSolution = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int btnResetName = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int btnSolveName = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int strAppName = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int strFirstCofficient = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int strSecondCofficient = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int strThirdCofficient = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int txtResult = 2131034119;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
