#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Exercise_1.Resource", IsApplication=true)]

namespace Exercise_1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040003
			public const int CornflowerBlue = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int Gainsboro = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int GhostWhite = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int pink = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050006
			public const int marginLarge = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int marginMedium = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int marginSmall = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int paddingSmall = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int textSizeMedium = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int textSizeSmall = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int textviewPadding = 2131034113;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int back_icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int fb = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int button1 = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int button2 = 2131165187;
			
			// aapt resource value: 0x7f070009
			public const int button3 = 2131165193;
			
			// aapt resource value: 0x7f070005
			public const int linearLayout1 = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int linearLayout2 = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int linearLayout3 = 2131165190;
			
			// aapt resource value: 0x7f07000a
			public const int switch1 = 2131165194;
			
			// aapt resource value: 0x7f070002
			public const int textView1 = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int textView2 = 2131165188;
			
			// aapt resource value: 0x7f070008
			public const int textView3 = 2131165192;
			
			// aapt resource value: 0x7f070000
			public const int toolbar1 = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int btnBack = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int btnSignUp = 2131099651;
			
			// aapt resource value: 0x7f06000c
			public const int btnTermsOfService = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int txtAgree = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int txtConfirmPasswordHint = 2131099658;
			
			// aapt resource value: 0x7f060004
			public const int txtConnectFacebook = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int txtEmailHint = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int txtFirstNameHint = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int txtLastNameHint = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int txtPasswordHint = 2131099657;
			
			// aapt resource value: 0x7f060002
			public const int txtSignUp = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int txtUsernameHint = 2131099656;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
