#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Exercise_67.Resource", IsApplication=true)]

namespace Exercise_67
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int black = 2130968577;
			
			// aapt resource value: 0x7f040007
			public const int colorAccent = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int colorPrimary = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int colorPrimaryDark = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int gray = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int green = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int red = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int white = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int layout_margin = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int text_size_small = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int view_margin_large = 2131034113;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int android = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int brackets = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int eye = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int information = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int leftarrow = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int password = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int phonecall = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int splash = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int user = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000a
			public const int btnLogin = 2131230730;
			
			// aapt resource value: 0x7f080006
			public const int btnRegister = 2131230726;
			
			// aapt resource value: 0x7f080002
			public const int button1 = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int button2 = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int editText1 = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int linearLayout1 = 2131230720;
			
			// aapt resource value: 0x7f080007
			public const int linearLayout2 = 2131230727;
			
			// aapt resource value: 0x7f080004
			public const int relativeLayout1 = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int textView2 = 2131230725;
			
			// aapt resource value: 0x7f080008
			public const int view1 = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int view2 = 2131230729;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Register = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060009
			public const int alreadyAccount = 2131099657;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int forgotPassword = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int noAccount = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int strLogin = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int strRegister = 2131099654;
			
			// aapt resource value: 0x7f060002
			public const int txtNameHint = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int txtPasswordHint = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int txtPhoneNumberHint = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int txtRefereCodeHint = 2131099656;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int MyTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int MyTheme_Splash = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
