#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CustomSeekbar.Resource", IsApplication=true)]

namespace CustomSeekbar
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int black = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int lightBlue = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int red = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int white = 2130968578;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050002
			public const int marginMedium = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int marginSmall = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int textSizeLarge = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int textSizeMedium = 2131034113;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int border_shadow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int custom_thumb = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int seekbar_progress = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int seekbar_style = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int sub = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int btnAdd = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int btnSub = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int btnUpdate = 2131165190;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int linearLayout2 = 2131165186;
			
			// aapt resource value: 0x7f070008
			public const int mySeekBar = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int progressshape = 2131165193;
			
			// aapt resource value: 0x7f070004
			public const int textView = 2131165188;
			
			// aapt resource value: 0x7f070007
			public const int textView3 = 2131165191;
			
			// aapt resource value: 0x7f070003
			public const int txtValue = 2131165187;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int my_seekbar = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int btnUpdate = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int currentValue = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int value = 2131099650;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
